SimpleCrud/Controllers/AdminController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using SimpleCrud.Data;
using SimpleCrud.Models;
using SimpleCrud.ViewModel;

namespace SimpleCrud.Controllers
{
    public class AdminController : Controller
    {
        private readonly AppDbContext Context;
        private readonly INotyfService _notyf;

        private readonly IWebHostEnvironment WebHostEnvironment;

        // private AppDbContext db = new AppDbContext();
        public AdminController(AppDbContext _context, IWebHostEnvironment webHostEnvironment, INotyfService notyf)
        {
            this.Context = _context;
            WebHostEnvironment = webHostEnvironment;
            _notyf = notyf;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public IActionResult RegisterInfo(AdminVM A)
        {
           
            if (ModelState.IsValid)
            {
                string password = BCrypt.Net.BCrypt.HashPassword(A.Password);
                var reg = new Admin
                {
                    AdminName = A.AdminName,
                    Email = A.Email,
                    Gender = A.Gender,
                    Phone = A.Phone,
                    Password = password
                };
                Context.Admins.Add(reg);
                Context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                TempData["ErrorMessage"] = "";

            }
            return View("Register");
        }
        public IActionResult LogOut()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            var storedCookies=Request.Cookies.Keys;
            foreach (var cookies in storedCookies)
            {
                Response.Cookies.Delete(cookies);
            }
                  
            return RedirectToAction("Index");
        }
       
    
    
    }
}

SimpleCrud/Controllers/FacultyController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimpleCrud.Data;
using SimpleCrud.Models;
using SimpleCrud.ViewModel;

namespace SimpleCrud.Controllers
{
    public class FacultyController : Controller
    {
        private readonly AppDbContext Context;
        private readonly INotyfService _notyf;

        private readonly IWebHostEnvironment WebHostEnvironment;

        // private AppDbContext db = new AppDbContext();
        public FacultyController(AppDbContext _context, IWebHostEnvironment webHostEnvironment, INotyfService notyf)
        {
            this.Context = _context;
            WebHostEnvironment = webHostEnvironment;
            _notyf = notyf;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View(Context.Faculties.ToList());
        }
        public IActionResult AddFaculty(FacultyVM faculty)
        {
            var facul = new Faculty
            {
                FacultyName = faculty.FacultyName
            };
            Context.Faculties.Add(facul);
            Context.SaveChanges();
            _notyf.Success("Success Notification");
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int? id)
        {
            var data = Context.Faculties.Find(id);
            Context.Faculties.Remove(data);
            Context.SaveChanges();
            _notyf.Error("Success Notification");
            return RedirectToAction("Index");
        }
        public IActionResult UpdateFaculty(FacultyVM faculty)
        {
            var data= Context.Faculties.Find(faculty.Id);
            data.FacultyName=faculty.FacultyName;
            Context.Faculties.Update(data);
            Context.SaveChanges();
            _notyf.Success("Success Notification");
            return RedirectToAction("Index");
        }

    }
}

SimpleCrud/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleCrud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/table.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimpleCrud.styles.css" asp-append-version="true" />
</head>
<body style="background:#E0ECF7;">
   
    <header style="background: #c5aa6a;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b><span style="color:#A5D732">Simple</span><span style="color:#6FA8DC">Crud</span></b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                     @if(User.Identity.IsAuthenticated){
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="color:white">
                                    Faculty
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="Index">Add Faculty</a>
                                    </li>
                                    
                                </ul>
                            </div>
                        </li>
                       
                        <li>
                        <div class="dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="color:white">
                                Student
                            </a>
                            <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Add Student</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="StudentInfo">Student Info</a>
                                    </li>
                               
                            </ul>
                        </div>
                      </li>
                       
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Details">Details</a>
                        </li>*@
                    </ul>
                    }
                </div>
            </div>
            @if(User.Identity.IsAuthenticated){
                <div class="d-flex m-2">
                    <div class="d-flex p-2">
                        <span> Welcome </span> <span class="ps-1 text-success"><b>@HttpContextAccessor.HttpContext.Session.GetString("Name")</b></span>

                     </div>
                    <div> <a class="btn btn-sm btn-danger" asp-action="LogOut" asp-controller="Admin"> SignOut </a></div>
                  </div>
               }else{
            <a type="button" class="btn btn-outline-primary me-3" asp-controller="Admin" asp-action="Index">Login</a>
            <a type="button" class="btn btn-outline-success me-2" asp-controller="Admin" asp-action="Register">Register</a>
               }
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-1">
            @RenderBody()
        </main>
    </div>
@*
    <footer class="border-top footer text-muted" style="background:#43464A;">
        <div class="container" style="color:white;">
            &copy; 2022 - SimpleCrud @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
     @*   </div>
    </footer>*@
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/table.js" asp-append-version="true"></script>
   
  
   
    
    @await Component.InvokeAsync("Notyf")
    @RenderSection("Scripts", required: false)
</body>
</html>